# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjRUBT78IpTmmNZIfeNDwIrueFJdhSPJ
"""

pip install streamlit

import streamlit as st
import joblib
import numpy as np

# Load model
model = joblib.load('best_model.pkl')

# Judul aplikasi
st.title("🎯 Prediksi Klasifikasi")
st.write("Masukkan data fitur untuk memprediksi kelas menggunakan model yang telah dioptimasi.")

# Buat input fitur (ini disesuaikan dengan jumlah fitur X kamu)
# Misal jumlah fitur = 4 (seperti pada dataset Iris atau yang mirip)
feature_1 = st.number_input("Fitur 1", value=0.0)
feature_2 = st.number_input("Fitur 2", value=0.0)
feature_3 = st.number_input("Fitur 3", value=0.0)
feature_4 = st.number_input("Fitur 4", value=0.0)

# Tombol prediksi
if st.button("Prediksi"):
    # Ubah input menjadi array dan lakukan prediksi
    input_data = np.array([[feature_1, feature_2, feature_3, feature_4]])

    # Jika kamu menyimpan scaler, load dan transform dulu:
    # scaler = joblib.load('scaler.pkl')
    # input_data = scaler.transform(input_data)

    prediction = model.predict(input_data)

    st.success(f"Hasil Prediksi: {prediction[0]}")